pub mod email;
pub mod email_manager;
pub mod email_sync;
pub mod imap;
pub mod smtp;
pub mod background;
pub mod conversation;
pub mod search;
pub mod imap_idle;
pub mod threading;
pub mod background_services;
pub mod agent;
pub mod automation_scheduler;
pub mod caldav;
pub mod caldav_sync;
pub mod oauth_refresh;
pub mod token_refresh;

pub use email::EmailService;
pub use email_manager::EmailManager;
pub use email_sync::EmailSyncService;
pub use imap::ImapService;
pub use smtp::SmtpService;
pub use conversation::ConversationService;
pub use search::SearchService;
pub use imap_idle::ImapIdleService;
pub use threading::{JwzThreading, ThreadableEmail, ThreadNode};
pub use background_services::BackgroundServiceManager;
pub mod attachment_enrichment;
pub use attachment_enrichment::AttachmentEnrichmentService;
pub use agent::{AgentEngine, LLMProvider, ProviderConfig, ToolRegistry};
pub use automation_scheduler::AutomationScheduler;
pub use caldav::CalDavClient;
pub use oauth_refresh::OAuthRefreshService;